/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/etablissements/{etablissement_id}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste les notes internes d'un établissement. */
        get: operations["lister"];
        put?: never;
        /**
         * Crée une note interne.
         * @description **`200` sur rejeu, pas `409`** — et c'est un choix, pas un raccourci. Un client hors ligne qui
         *     vide sa file ne doit pas voir d'erreur pour une écriture que le serveur a déjà acceptée : le
         *     principe VI exige que le rejeu soit idempotent, et un `409` obligerait chaque appelant à
         *     traiter un cas d'erreur qui n'en est pas un. Le corps renvoyé est la note **telle qu'elle est
         *     en base** — le serveur fait foi en conflit.
         */
        post: operations["creer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Corps de création d'une note. */
        CreerNoteRequete: {
            /**
             * Format: date-time
             * @description Indicatif : ordre d'affichage local. **Jamais utilisé par une règle métier.**
             */
            horodatage_client?: string | null;
            /**
             * Format: uuid
             * @description UUID v7 **généré par le client**. C'est lui qui rend le rejeu inoffensif : trois envois du
             *     même identifiant produisent un seul enregistrement.
             */
            id: string;
            /** @description Texte de la note — entre 1 et 2000 caractères après nettoyage. */
            texte: string;
        };
        /** @description Une note interne, telle qu'elle existe en base. */
        NoteEtablissement: {
            /** Format: uuid */
            auteur_compte_id: string;
            /**
             * Format: date-time
             * @description Horodatage d'**autorité serveur**. C'est lui qui fait foi.
             */
            cree_le: string;
            /** Format: uuid */
            etablissement_id: string;
            /**
             * Format: date-time
             * @description Indicatif — ordre d'affichage local. **Jamais utilisé par une règle métier.**
             */
            horodatage_client?: string | null;
            /** Format: uuid */
            id: string;
            texte: string;
        };
        /** @description Une page de notes. */
        PageNotes: {
            /** Format: int64 */
            decalage: number;
            elements: components["schemas"]["NoteEtablissement"][];
            /** Format: int64 */
            limite: number;
            /** Format: int64 */
            total: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    lister: {
        parameters: {
            query?: {
                /** @description Nombre maximal d'éléments renvoyés. Défaut 50, plafond 200. */
                limite?: number;
                /** @description Nombre d'éléments ignorés en tête. */
                decalage?: number;
            };
            header?: never;
            path: {
                /** @description Identifiant de l'établissement */
                etablissement_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Notes de l'établissement */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageNotes"];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Permission absente */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Établissement inconnu */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    creer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant de l'établissement */
                etablissement_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreerNoteRequete"];
            };
        };
        responses: {
            /** @description Note déjà créée (rejeu idempotent) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteEtablissement"];
                };
            };
            /** @description Note créée */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteEtablissement"];
                };
            };
            /** @description Requête invalide */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Permission absente */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Établissement inconnu */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
